### ISSUE TITLE
[Bug] [ERROR] regex compilation failed

### ISSUE THREAD

**Issue by Kristinita** [jfcherng/Sublime-AutoSetSyntax#6]
### Summary

I get errors in console, when I restart Sublime Text. 
### Expected behavior

No errors in console.
### Actual behavior

When I restart Sublime Text, I get this messages in console:

```
AutoSetSyntax: [ERROR] regex compilation failed in "Packages/Markdown/MultiMarkdown.sublime-syntax": ^Format:\s*(?i:complete)\s*$
ERROR:AutoSetSyntax:regex compilation failed in "Packages/Markdown/MultiMarkdown.sublime-syntax": ^Format:\s*(?i:complete)\s*$
AutoSetSyntax: [ERROR] regex compilation failed in "Packages/MarkdownEditing/MultiMarkdown.tmLanguage": ^Format:\s*(?i:complete)\s*$
ERROR:AutoSetSyntax:regex compilation failed in "Packages/MarkdownEditing/MultiMarkdown.tmLanguage": ^Format:\s*(?i:complete)\s*$
AutoSetSyntax: [INFO] match syntax file "ANSIescape/ANSI.tmLanguage" with "Packages/ANSIescape/ANSI.tmLanguage"
INFO:AutoSetSyntax:match syntax file "ANSIescape/ANSI.tmLanguage" with "Packages/ANSIescape/ANSI.tmLanguage"
```

Sometimes Sublime Text freezes and I have to force close the Sublime Text and start Sublime Text again.
### Steps to reproduce

I restart Sublime Text and I get this errors.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by jfcherng** [comment]
That error message means the `first_line_match` in `Packages/Markdown/MultiMarkdown.sublime-syntax` is not a valid regex. But this is a official package and I am using 3216 Win7 well without a problem. And I just check the `first_line_match` in the error message is the same in my `Packages/Markdown/MultiMarkdown.sublime-syntax`. So, I do not really know what is happening here.

Any recent change to your ST?

It may not be related but would you please show me your settings for `AutoSetSyntax`?

**Comment by Kristinita** [comment]
@jfcherng , this problem reproduced for me in new Sublime Text 3126 without plugins and user settings for AutoSetSyntax and other plugins. I get in console:

```
AutoSetSyntax: [ERROR] regex compilation failed in "Packages/Markdown/MultiMarkdown.sublime-syntax": ^Format:\s*(?i:complete)\s*$
```

Thanks.

**Comment by jfcherng** [comment]
Okay. I can reproduce it now. I will investigate it when I am available.

**Comment by jfcherng** [comment]
I am going to close this issue since my PR to the official ST package repo has been merged.

This issue should be fixed in the next ST release (or you may use the latest packages in the official repo by yourself).

**Comment by Kristinita** [comment]
@jfcherng , I change my `E:\Sublime Text 3\Data\Packages\Markdown\MultiMarkdown.sublime-syntax` to https://raw.githubusercontent.com/sublimehq/Packages/master/Markdown/MultiMarkdown.sublime-syntax → I restart Sublime Text 2 times, but I still get messages in console:

```
AutoSetSyntax: [ERROR] regex compilation failed in "Packages/MarkdownEditing/MultiMarkdown.tmLanguage": ^Format:\s*(?i:complete)\s*$
ERROR:AutoSetSyntax:regex compilation failed in "Packages/MarkdownEditing/MultiMarkdown.tmLanguage": ^Format:\s*(?i:complete)\s*$
AutoSetSyntax: [INFO] match syntax file "ANSIescape/ANSI.tmLanguage" with "Packages/ANSIescape/ANSI.tmLanguage"
INFO:AutoSetSyntax:match syntax file "ANSIescape/ANSI.tmLanguage" with "Packages/ANSIescape/ANSI.tmLanguage"
```

Thanks.

**Comment by jfcherng** [comment]
From the debug message, obviously, ST is still using the old syntax cache.
You can delete the `Cache` folder safely and then ST would generate a new one for you.
The `Cache` folder is under the data folder which can be found in https://www.sublimetext.com/docs/3/revert.html.

*\* **Caution**: You only need to delete the `Cache` folder. Do **NOT** delete the whole data folder.

**Comment by Kristinita** [comment]
@jfcherng , I close Sublime Text → I delete `Cache` folder → I run Sublime Text → I still get the same error. Thanks.

**Comment by jfcherng** [comment]
Ah, I am sorry that I did not notice that it was `Packages/MarkdownEditing/MultiMarkdown.tmLanguage` in the error log but not a package of ST official. It should be reported to `MarkdownEditing` package since it looks like they directly copy the `first_line_match` from ST's official Markdown package.

To fix it by yourself, you can still replace the `first_line_match` in the file, which is reported in the error log, with [this one](https://github.com/sublimehq/Packages/pull/657/commits/22175e8dd9c578d466b5a4f8e7cca2a354fcace1#diff-812884c83b06ed0c4d0e363a66c05315R5). `.sublime-package` is actually a zip file. You can unzip it, modified files, zip them back, change the extension from `.zip` to `.sublime-package` and finally replace the old buggy one.

**Comment by Kristinita** [comment]
Thanks, it work for me!

> To fix it by yourself, you can still replace the first_line_match in the file, which is reported in the error log, with this one. .sublime-package is actually a zip file. You can unzip it, modified files, zip them back, change the extension from .zip to .sublime-package and finally replace the old buggy one.

Easier [`PackageResourceViewer: Extract Package`](https://github.com/skuroda/PackageResourceViewer#commands).
